name: CI

on:
  push:
    branches: [main]
    tags: ['*']
  pull_request:
  workflow_dispatch:

concurrency:
  # cancel intermediate builds of the same branch or pull request
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.threads }} threads
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version: ['1.10', '1']
        os: [ubuntu-latest]
        threads: ['1', '4']
        include:
          - version: '1'
            os: macos-latest
            threads: '4'
          - version: '1'
            os: windows-latest
            threads: '4'
    env:
      JULIA_NUM_THREADS: ${{ matrix.threads }}
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1

  extensions:
    name: MLDatasets extension
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      actions: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - name: Install dependencies
        run: julia --project=test/extensions -e 'using Pkg; Pkg.instantiate()'
      - name: Run tests
        run: julia --project=test/extensions test/extensions/runtests.jl
        env:
          DATADEPS_ALWAYS_ACCEPT: 'true'
